
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 25 02:23:30 CST 2018
//----------------------------------------------------

package GeneradorCJS;

/** CUP generated class containing symbol constants. */
public class symCJS {
  /* terminals */
  public static final int PAR_DER = 25;
  public static final int CASO = 41;
  public static final int MULT = 11;
  public static final int MENSAJE = 47;
  public static final int IMPRIMIR = 36;
  public static final int OBSERVADOR = 44;
  public static final int SI = 34;
  public static final int FUNCION = 48;
  public static final int DOCUMENTO = 43;
  public static final int DIFERENTE = 16;
  public static final int OBTENER = 49;
  public static final int DOS_PUNTOS = 31;
  public static final int DATE = 5;
  public static final int NOT = 23;
  public static final int AND = 21;
  public static final int MAYORQUE = 17;
  public static final int IGUAL = 15;
  public static final int SINO = 35;
  public static final int OR = 22;
  public static final int MIENTRAS = 32;
  public static final int LLA_DER = 26;
  public static final int DIV = 12;
  public static final int INCREMENTO = 13;
  public static final int ATEXTO = 45;
  public static final int SELECCIONAR = 40;
  public static final int DIMV = 37;
  public static final int PUNTO_COMA = 29;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int SETELEMENTO = 46;
  public static final int MAYORIGUALQUE = 19;
  public static final int TRUE = 8;
  public static final int DECREMENTO = 14;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int CADENA = 4;
  public static final int MENOS = 10;
  public static final int PAR_IZQ = 24;
  public static final int MENORQUE = 18;
  public static final int NUMERICO = 3;
  public static final int DETENER = 39;
  public static final int PUNTO = 28;
  public static final int MENORIGUALQUE = 20;
  public static final int PARA = 33;
  public static final int CONTEO = 50;
  public static final int RETORNAR = 38;
  public static final int DATE_T = 6;
  public static final int FALSE = 7;
  public static final int LLA_IZQ = 27;
  public static final int DEFECTO = 42;
  public static final int MAS = 9;
}

