
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 02 20:46:14 CST 2018
//----------------------------------------------------

package GeneradorCJS;

/** CUP generated class containing symbol constants. */
public class symCJS {
  /* terminals */
  public static final int PAR_DER = 27;
  public static final int CASO = 43;
  public static final int POT = 13;
  public static final int MULT = 11;
  public static final int MENSAJE = 49;
  public static final int IMPRIMIR = 38;
  public static final int OBSERVADOR = 46;
  public static final int SI = 36;
  public static final int FUNCION = 50;
  public static final int DOCUMENTO = 45;
  public static final int DIFERENTE = 18;
  public static final int OBTENER = 51;
  public static final int DOS_PUNTOS = 33;
  public static final int DATE = 5;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int MAYORQUE = 19;
  public static final int IGUAL = 17;
  public static final int SINO = 37;
  public static final int OR = 24;
  public static final int MIENTRAS = 34;
  public static final int LLA_DER = 28;
  public static final int DIV = 12;
  public static final int INCREMENTO = 15;
  public static final int ATEXTO = 47;
  public static final int SELECCIONAR = 42;
  public static final int DIMV = 39;
  public static final int PUNTO_COMA = 31;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int SETELEMENTO = 48;
  public static final int MAYORIGUALQUE = 21;
  public static final int TRUE = 8;
  public static final int DECREMENTO = 16;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int CADENA = 4;
  public static final int MENOS = 10;
  public static final int MOD = 14;
  public static final int PAR_IZQ = 26;
  public static final int MENORQUE = 20;
  public static final int NUMERICO = 3;
  public static final int DETENER = 41;
  public static final int PUNTO = 30;
  public static final int MENORIGUALQUE = 22;
  public static final int PARA = 35;
  public static final int CONTEO = 52;
  public static final int RETORNAR = 40;
  public static final int DATE_T = 6;
  public static final int FALSE = 7;
  public static final int LLA_IZQ = 29;
  public static final int DEFECTO = 44;
  public static final int MAS = 9;
}

