
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 19 00:26:07 CST 2018
//----------------------------------------------------

package GeneradorCCSS;

import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;
import AST.Nodo;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Feb 19 00:26:07 CST 2018
  */
public class parserCCSS extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parserCCSS() {super();}

  /** Constructor which sets the default scanner. */
  public parserCCSS(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserCCSS(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\055\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\006\000\002\004\005" +
    "\000\002\013\004\000\002\013\003\000\002\005\010\000" +
    "\002\005\010\000\002\005\007\000\002\005\007\000\002" +
    "\006\004\000\002\006\003\000\002\007\006\000\002\007" +
    "\006\000\002\007\006\000\002\007\006\000\002\007\006" +
    "\000\002\007\006\000\002\007\012\000\002\007\006\000" +
    "\002\007\014\000\002\007\006\000\002\007\006\000\002" +
    "\014\003\000\002\014\003\000\002\010\005\000\002\010" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003\000\002\011\005\000" +
    "\002\011\005\000\002\011\005\000\002\011\005\000\002" +
    "\011\004\000\002\011\005\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\004\004\004\001\002\000\004\011\012\001" +
    "\002\000\006\002\ufffe\004\ufffe\001\002\000\004\002\011" +
    "\001\002\000\006\002\000\004\004\001\002\000\006\002" +
    "\uffff\004\uffff\001\002\000\004\002\001\001\002\000\010" +
    "\012\013\037\015\042\014\001\002\000\006\002\ufffc\004" +
    "\ufffc\001\002\000\004\013\153\001\002\000\004\013\022" +
    "\001\002\000\010\012\ufffa\037\ufffa\042\ufffa\001\002\000" +
    "\010\012\020\037\015\042\014\001\002\000\006\002\ufffd" +
    "\004\ufffd\001\002\000\010\012\ufffb\037\ufffb\042\ufffb\001" +
    "\002\000\004\004\023\001\002\000\004\014\024\001\002" +
    "\000\004\015\025\001\002\000\036\012\ufff6\024\040\025" +
    "\032\026\041\027\034\030\033\031\042\032\036\033\027" +
    "\034\026\035\031\036\037\037\ufff6\042\ufff6\001\002\000" +
    "\004\016\142\001\002\000\004\016\137\001\002\000\036" +
    "\012\ufff8\024\040\025\032\026\041\027\034\030\033\031" +
    "\042\032\036\033\027\034\026\035\031\036\037\037\ufff8" +
    "\042\ufff8\001\002\000\004\016\133\001\002\000\004\016" +
    "\130\001\002\000\004\016\125\001\002\000\004\016\122" +
    "\001\002\000\036\012\ufff4\024\ufff4\025\ufff4\026\ufff4\027" +
    "\ufff4\030\ufff4\031\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4" +
    "\036\ufff4\037\ufff4\042\ufff4\001\002\000\004\016\111\001" +
    "\002\000\004\016\106\001\002\000\004\016\103\001\002" +
    "\000\004\016\070\001\002\000\004\016\043\001\002\000" +
    "\020\004\045\005\044\006\046\007\050\010\053\013\052" +
    "\021\047\001\002\000\022\012\uffd8\014\uffd8\015\uffd8\017" +
    "\uffd8\020\uffd8\021\uffd8\022\uffd8\023\uffd8\001\002\000\022" +
    "\012\uffd9\014\uffd9\015\uffd9\017\uffd9\020\uffd9\021\uffd9\022" +
    "\uffd9\023\uffd9\001\002\000\022\012\uffd7\014\uffd7\015\uffd7" +
    "\017\uffd7\020\uffd7\021\uffd7\022\uffd7\023\uffd7\001\002\000" +
    "\020\004\045\005\044\006\046\007\050\010\053\013\052" +
    "\021\047\001\002\000\022\012\uffd6\014\uffd6\015\uffd6\017" +
    "\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6\001\002\000\014" +
    "\015\066\020\055\021\056\022\060\023\057\001\002\000" +
    "\020\004\045\005\044\006\046\007\050\010\053\013\052" +
    "\021\047\001\002\000\022\012\uffd5\014\uffd5\015\uffd5\017" +
    "\uffd5\020\uffd5\021\uffd5\022\uffd5\023\uffd5\001\002\000\014" +
    "\014\061\020\055\021\056\022\060\023\057\001\002\000" +
    "\020\004\045\005\044\006\046\007\050\010\053\013\052" +
    "\021\047\001\002\000\020\004\045\005\044\006\046\007" +
    "\050\010\053\013\052\021\047\001\002\000\020\004\045" +
    "\005\044\006\046\007\050\010\053\013\052\021\047\001" +
    "\002\000\020\004\045\005\044\006\046\007\050\010\053" +
    "\013\052\021\047\001\002\000\022\012\uffda\014\uffda\015" +
    "\uffda\017\uffda\020\uffda\021\uffda\022\uffda\023\uffda\001\002" +
    "\000\022\012\uffdd\014\uffdd\015\uffdd\017\uffdd\020\uffdd\021" +
    "\uffdd\022\uffdd\023\uffdd\001\002\000\022\012\uffdc\014\uffdc" +
    "\015\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\023\uffdc\001" +
    "\002\000\022\012\uffde\014\uffde\015\uffde\017\uffde\020\uffde" +
    "\021\uffde\022\060\023\057\001\002\000\022\012\uffdf\014" +
    "\uffdf\015\uffdf\017\uffdf\020\uffdf\021\uffdf\022\060\023\057" +
    "\001\002\000\036\012\uffee\024\uffee\025\uffee\026\uffee\027" +
    "\uffee\030\uffee\031\uffee\032\uffee\033\uffee\034\uffee\035\uffee" +
    "\036\uffee\037\uffee\042\uffee\001\002\000\022\012\uffdb\014" +
    "\uffdb\015\uffdb\017\uffdb\020\uffdb\021\uffdb\022\060\023\057" +
    "\001\002\000\014\043\072\044\074\045\076\046\075\047" +
    "\077\001\002\000\006\015\uffe5\017\uffe5\001\002\000\006" +
    "\015\uffe1\017\uffe1\001\002\000\006\015\101\017\100\001" +
    "\002\000\006\015\uffe2\017\uffe2\001\002\000\006\015\uffe3" +
    "\017\uffe3\001\002\000\006\015\uffe4\017\uffe4\001\002\000" +
    "\006\015\uffe0\017\uffe0\001\002\000\014\043\072\044\074" +
    "\045\076\046\075\047\077\001\002\000\036\012\ufff1\024" +
    "\ufff1\025\ufff1\026\ufff1\027\ufff1\030\ufff1\031\ufff1\032\ufff1" +
    "\033\ufff1\034\ufff1\035\ufff1\036\ufff1\037\ufff1\042\ufff1\001" +
    "\002\000\006\015\uffe6\017\uffe6\001\002\000\020\004\045" +
    "\005\044\006\046\007\050\010\053\013\052\021\047\001" +
    "\002\000\014\015\105\020\055\021\056\022\060\023\057" +
    "\001\002\000\036\012\ufff3\024\ufff3\025\ufff3\026\ufff3\027" +
    "\ufff3\030\ufff3\031\ufff3\032\ufff3\033\ufff3\034\ufff3\035\ufff3" +
    "\036\ufff3\037\ufff3\042\ufff3\001\002\000\020\004\045\005" +
    "\044\006\046\007\050\010\053\013\052\021\047\001\002" +
    "\000\014\015\110\020\055\021\056\022\060\023\057\001" +
    "\002\000\036\012\uffe9\024\uffe9\025\uffe9\026\uffe9\027\uffe9" +
    "\030\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\035\uffe9\036" +
    "\uffe9\037\uffe9\042\uffe9\001\002\000\004\011\112\001\002" +
    "\000\020\004\045\005\044\006\046\007\050\010\053\013" +
    "\052\021\047\001\002\000\014\017\114\020\055\021\056" +
    "\022\060\023\057\001\002\000\006\040\116\041\117\001" +
    "\002\000\004\012\120\001\002\000\004\012\uffe8\001\002" +
    "\000\004\012\uffe7\001\002\000\004\015\121\001\002\000" +
    "\036\012\uffed\024\uffed\025\uffed\026\uffed\027\uffed\030\uffed" +
    "\031\uffed\032\uffed\033\uffed\034\uffed\035\uffed\036\uffed\037" +
    "\uffed\042\uffed\001\002\000\020\004\045\005\044\006\046" +
    "\007\050\010\053\013\052\021\047\001\002\000\014\015" +
    "\124\020\055\021\056\022\060\023\057\001\002\000\036" +
    "\012\ufff0\024\ufff0\025\ufff0\026\ufff0\027\ufff0\030\ufff0\031" +
    "\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0\036\ufff0\037\ufff0" +
    "\042\ufff0\001\002\000\020\004\045\005\044\006\046\007" +
    "\050\010\053\013\052\021\047\001\002\000\014\015\127" +
    "\020\055\021\056\022\060\023\057\001\002\000\036\012" +
    "\uffef\024\uffef\025\uffef\026\uffef\027\uffef\030\uffef\031\uffef" +
    "\032\uffef\033\uffef\034\uffef\035\uffef\036\uffef\037\uffef\042" +
    "\uffef\001\002\000\020\004\045\005\044\006\046\007\050" +
    "\010\053\013\052\021\047\001\002\000\014\015\132\020" +
    "\055\021\056\022\060\023\057\001\002\000\036\012\ufff2" +
    "\024\ufff2\025\ufff2\026\ufff2\027\ufff2\030\ufff2\031\ufff2\032" +
    "\ufff2\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\042\ufff2" +
    "\001\002\000\020\004\045\005\044\006\046\007\050\010" +
    "\053\013\052\021\047\001\002\000\014\015\135\020\055" +
    "\021\056\022\060\023\057\001\002\000\036\012\uffea\024" +
    "\uffea\025\uffea\026\uffea\027\uffea\030\uffea\031\uffea\032\uffea" +
    "\033\uffea\034\uffea\035\uffea\036\uffea\037\uffea\042\uffea\001" +
    "\002\000\036\012\ufff5\024\ufff5\025\ufff5\026\ufff5\027\ufff5" +
    "\030\ufff5\031\ufff5\032\ufff5\033\ufff5\034\ufff5\035\ufff5\036" +
    "\ufff5\037\ufff5\042\ufff5\001\002\000\020\004\045\005\044" +
    "\006\046\007\050\010\053\013\052\021\047\001\002\000" +
    "\014\015\141\020\055\021\056\022\060\023\057\001\002" +
    "\000\036\012\uffec\024\uffec\025\uffec\026\uffec\027\uffec\030" +
    "\uffec\031\uffec\032\uffec\033\uffec\034\uffec\035\uffec\036\uffec" +
    "\037\uffec\042\uffec\001\002\000\004\011\143\001\002\000" +
    "\020\004\045\005\044\006\046\007\050\010\053\013\052" +
    "\021\047\001\002\000\014\017\145\020\055\021\056\022" +
    "\060\023\057\001\002\000\020\004\045\005\044\006\046" +
    "\007\050\010\053\013\052\021\047\001\002\000\014\017" +
    "\147\020\055\021\056\022\060\023\057\001\002\000\020" +
    "\004\045\005\044\006\046\007\050\010\053\013\052\021" +
    "\047\001\002\000\014\012\151\020\055\021\056\022\060" +
    "\023\057\001\002\000\004\015\152\001\002\000\036\012" +
    "\uffeb\024\uffeb\025\uffeb\026\uffeb\027\uffeb\030\uffeb\031\uffeb" +
    "\032\uffeb\033\uffeb\034\uffeb\035\uffeb\036\uffeb\037\uffeb\042" +
    "\uffeb\001\002\000\004\004\154\001\002\000\004\014\155" +
    "\001\002\000\004\015\156\001\002\000\036\012\ufff7\024" +
    "\040\025\032\026\041\027\034\030\033\031\042\032\036" +
    "\033\027\034\026\035\031\036\037\037\ufff7\042\ufff7\001" +
    "\002\000\036\012\ufff9\024\040\025\032\026\041\027\034" +
    "\030\033\031\042\032\036\033\027\034\026\035\031\036" +
    "\037\037\ufff9\042\ufff9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\010\002\005\003\006\004\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\005\015\013\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\027\007\034\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\135\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\053\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\064\001\001\000\004\011\063\001\001" +
    "\000\004\011\062\001\001\000\004\011\061\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\072\012\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\101\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\103\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\106\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\112\001\001\000\002" +
    "\001\001\000\004\014\114\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\122\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\125\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\130\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\133\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\137\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\143\001\001\000\002\001\001\000" +
    "\004\011\145\001\001\000\002\001\001\000\004\011\147" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\006\156\007\034\001\001\000\004\007\135\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserCCSS$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserCCSS$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserCCSS$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


//Codigo visible

    /* Metodo para errores sintacticos*/
	
    public void sintax_error(Symbol s){
        System.out.println("Error en la linea: " + (s.right+1) + " Columna " + s.left + ". Token #" + s.value + " no reconocido.");
    }

    /* Método errores fatales */

    public void errores_fatales(Symbol s) throws Exception{
        JOptionPane.showMessageDialog(null, "Error Sintactico en la linea: " + (s.right+1) + " Columna " + s.left + ". Token #" + s.value + " no reconocido.");
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parserCCSS$actions {

//Codigo de acciones
    

  private final parserCCSS parser;

  /** Constructor */
  CUP$parserCCSS$actions(parserCCSS parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parserCCSS$do_action(
    int                        CUP$parserCCSS$act_num,
    java_cup.runtime.lr_parser CUP$parserCCSS$parser,
    java.util.Stack            CUP$parserCCSS$stack,
    int                        CUP$parserCCSS$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserCCSS$result;

      /* select the action based on the action number */
      switch (CUP$parserCCSS$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // E ::= CADENA 
            {
              Nodo RESULT =null;
		int cadleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		 
                    RESULT = new Nodo(ConsCSS.CAD,cad.substring(1, cad.length()-1)); 
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // E ::= FALSE 
            {
              Nodo RESULT =null;
		int tfleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int tfright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String tf = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		 
                    RESULT = new Nodo(ConsCSS.BOOL,tf); 
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // E ::= TRUE 
            {
              Nodo RESULT =null;
		int ttleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int ttright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String tt = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		 
                    RESULT = new Nodo(ConsCSS.BOOL,tt); 
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // E ::= NUM 
            {
              Nodo RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		  
                    RESULT = new Nodo(ConsCSS.E);
                    RESULT.addHijo(new Nodo(ConsCSS.NUM,num));
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // E ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		  
                    RESULT = new Nodo(ConsCSS.E);
                    RESULT.addHijo(new Nodo(ConsCSS.ID,id));
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // E ::= PAR_IZQ E PAR_DER 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		  
                    RESULT = e;
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // E ::= MENOS E 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.E);
                    Nodo n = new Nodo(ConsCSS.MENOS);
                    RESULT.addHijo(n,e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // E ::= E DIV E 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo e2 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		 
                    RESULT = new Nodo(ConsCSS.E);
                    Nodo n = new Nodo(ConsCSS.DIV);
                    n.addHijo(e1,e2);
                    RESULT.addHijo(n);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // E ::= E POR E 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo e2 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.E);
                    Nodo n = new Nodo(ConsCSS.POR);
                    n.addHijo(e1,e2);
                    RESULT.addHijo(n);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // E ::= E MENOS E 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo e2 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.E);
                    Nodo n = new Nodo(ConsCSS.MENOS);
                    n.addHijo(e1,e2);
                    RESULT.addHijo(n);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // E ::= E MAS E 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		int signoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int signoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		String signo = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo e2 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.E);
                    Nodo n = new Nodo(ConsCSS.MAS);
                    n.addHijo(e1,e2);
                    RESULT.addHijo(n);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("E",7, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // FORM ::= capital 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String formato = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.CAPITAL);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("FORM",8, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // FORM ::= negrilla 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String formato = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.NEGRILLA);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("FORM",8, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // FORM ::= cursiva 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String formato = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.CURSIVA);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("FORM",8, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // FORM ::= minuscula 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String formato = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.MINUSCULA);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("FORM",8, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // FORM ::= mayuscula 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		String formato = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.MAYUSCULA);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("FORM",8, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // L_FORM ::= FORM 
            {
              Nodo RESULT =null;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo formato = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.L_FORM);
                    RESULT.addHijo(formato);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_FORM",6, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // L_FORM ::= L_FORM COMA FORM 
            {
              Nodo RESULT =null;
		int l_formleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int l_formright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo l_form = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		int formatoleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int formatoright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo formato = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = l_form;
                    RESULT.addHijo(formato);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_FORM",6, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // AREA ::= vertical 
            {
              Nodo RESULT =null;
		
                    RESULT = new Nodo(ConsCSS.VERTI);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("AREA",10, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // AREA ::= horizontal 
            {
              Nodo RESULT =null;
		
                    RESULT = new Nodo(ConsCSS.HORI);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("AREA",10, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // SEN ::= colorText IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.COLOR_TEXT);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SEN ::= opaque IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.OPAQUE);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // SEN ::= borde IGUAL COR_IZQ E COMA E COMA E COR_DER PUNTO_COMA 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-6)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-6)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).right;
		Nodo e2 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo e3 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		
                    RESULT = new Nodo(ConsCSS.BORDE);
                    RESULT.addHijo(e1,e2,e3);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-9)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // SEN ::= visible IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.VISIBLE);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SEN ::= autoredimension IGUAL COR_IZQ E COMA AREA COR_DER PUNTO_COMA 
            {
              Nodo RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).right;
		Nodo e1 = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		
                    RESULT = new Nodo(ConsCSS.AUTOREDIM);
                    RESULT.addHijo(e1,a);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-7)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // SEN ::= fondoElemento IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.FONDOELE);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SEN ::= tamTex IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.TAMTEX);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SEN ::= letra IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.LETRA);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SEN ::= formato IGUAL L_FORM PUNTO_COMA 
            {
              Nodo RESULT =null;
		int l_formleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int l_formright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo l_form = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.FORMATO);
                    RESULT.addHijo(l_form);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SEN ::= texto IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.TEXTO);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SEN ::= alineado IGUAL E PUNTO_COMA 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.ALINEADO);
                    RESULT.addHijo(e);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("SEN",5, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // L_SEN ::= SEN 
            {
              Nodo RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo s = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.L_SEN);
                    RESULT.addHijo(s);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_SEN",4, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // L_SEN ::= L_SEN SEN 
            {
              Nodo RESULT =null;
		int l_senleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int l_senright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo l_sen = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo s = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = l_sen;
                    RESULT.addHijo(s);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_SEN",4, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ATRIB ::= id_token PAR_IZQ ID PAR_DER PUNTO_COMA 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		
                    RESULT = new Nodo(ConsCSS.ATRIB_ID);
                    RESULT.addHijo(new Nodo(ConsCSS.ID,id));
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ATRIB ::= grupo PAR_IZQ ID PAR_DER PUNTO_COMA 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		
                    RESULT = new Nodo(ConsCSS.ATRIB_G);
                    RESULT.addHijo(new Nodo(ConsCSS.ID,id));
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-4)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ATRIB ::= id_token PAR_IZQ ID PAR_DER PUNTO_COMA L_SEN 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.ATRIB_ID);
                    RESULT.addHijo(new Nodo(ConsCSS.ID,id));
                    RESULT.addHijo(l);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-5)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ATRIB ::= grupo PAR_IZQ ID PAR_DER PUNTO_COMA L_SEN 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.ATRIB_G);
                    RESULT.addHijo(new Nodo(ConsCSS.ID,id));
                    RESULT.addHijo(l);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("ATRIB",3, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-5)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // L_ATRIB ::= ATRIB 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.L_ATRIB);
                    RESULT.addHijo(a);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_ATRIB",9, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // L_ATRIB ::= L_ATRIB ATRIB 
            {
              Nodo RESULT =null;
		int l_atribleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int l_atribright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo l_atrib = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = l_atrib;
                    RESULT.addHijo(a);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_ATRIB",9, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DEF ::= ID COR_IZQ COR_DER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)).value;
		
                    RESULT = new Nodo(ConsCSS.DEF);
                    RESULT.addHijo(ConsCSS.ID,id);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("DEF",2, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-2)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // DEF ::= ID COR_IZQ L_ATRIB COR_DER 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		
                    RESULT = new Nodo(ConsCSS.DEF);
                    RESULT.addHijo(ConsCSS.ID,id);
                    RESULT.addHijo(l);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("DEF",2, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-3)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // L_DEF ::= DEF 
            {
              Nodo RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int defright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo def = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.L_DEF);
                    RESULT.addHijo(def);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_DEF",1, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // L_DEF ::= L_DEF DEF 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		int defleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int defright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo def = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = l;
                    RESULT.addHijo(def);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("L_DEF",1, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= L_DEF 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()).right;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.peek()).value;
		
                    RESULT = new Nodo(ConsCSS.INICIO);
                    RESULT.addHijo(l);
                
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          return CUP$parserCCSS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)).value;
		RESULT = start_val;
              CUP$parserCCSS$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.elementAt(CUP$parserCCSS$top-1)), ((java_cup.runtime.Symbol)CUP$parserCCSS$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserCCSS$parser.done_parsing();
          return CUP$parserCCSS$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

