
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 17 12:12:38 CST 2018
//----------------------------------------------------

package GeneradorCCSS;

/** CUP generated class containing symbol constants. */
public class symCCSS {
  /* terminals */
  public static final int t_colorText = 28;
  public static final int PAR_DER = 10;
  public static final int t_minuscula = 34;
  public static final int t_autoredimension = 24;
  public static final int POR = 16;
  public static final int t_texto = 19;
  public static final int t_borde = 26;
  public static final int COR_DER = 8;
  public static final int t_id = 29;
  public static final int t_fondoElemento = 23;
  public static final int t_visible = 25;
  public static final int IGUAL = 12;
  public static final int t_capital = 35;
  public static final int DIV = 17;
  public static final int t_tamTex = 22;
  public static final int NUM = 3;
  public static final int t_opaque = 27;
  public static final int t_mayuscula = 33;
  public static final int PUNTO_COMA = 11;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 6;
  public static final int MENOS = 15;
  public static final int t_letra = 21;
  public static final int PAR_IZQ = 9;
  public static final int t_grupo = 30;
  public static final int t_formato = 20;
  public static final int t_negrilla = 31;
  public static final int t_cursiva = 32;
  public static final int COR_IZQ = 7;
  public static final int FALSE = 5;
  public static final int t_alineado = 18;
  public static final int MAS = 14;
}

