
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 28 01:11:20 CST 2018
//----------------------------------------------------

package GeneradorCCSS;

/** CUP generated class containing symbol constants. */
public class symCCSS {
  /* terminals */
  public static final int PAR_DER = 10;
  public static final int mayuscula = 35;
  public static final int fondoElemento = 23;
  public static final int POR = 16;
  public static final int tamTex = 22;
  public static final int opaque = 27;
  public static final int negrilla = 33;
  public static final int derecha = 40;
  public static final int COR_DER = 8;
  public static final int letra = 21;
  public static final int IGUAL = 12;
  public static final int autoredimension = 24;
  public static final int grupo = 32;
  public static final int alineado = 18;
  public static final int DIV = 17;
  public static final int NUM = 3;
  public static final int justificado = 39;
  public static final int vertical = 31;
  public static final int PUNTO_COMA = 11;
  public static final int ID = 2;
  public static final int visible = 25;
  public static final int EOF = 0;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int capital = 37;
  public static final int COMA = 13;
  public static final int CADENA = 6;
  public static final int MENOS = 15;
  public static final int horizontal = 30;
  public static final int PAR_IZQ = 9;
  public static final int colorText = 28;
  public static final int minuscula = 36;
  public static final int centrado = 38;
  public static final int id_token = 29;
  public static final int texto = 19;
  public static final int izquierda = 41;
  public static final int COR_IZQ = 7;
  public static final int formato = 20;
  public static final int borde = 26;
  public static final int FALSE = 5;
  public static final int cursiva = 34;
  public static final int MAS = 14;
}

