/* The following code was generated by JFlex 1.6.1 */

package GeneradorCHTML;

import java_cup.runtime.Symbol;
//Inicio

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/GeneradorCHTML/LexicoCHTML.flex</tt>
 */
public class scannerCH implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO = 2;
  public static final int TEXTO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  7,  9, 46, 10,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     7, 11,  5, 11, 11, 11, 11,  0, 15, 16, 11, 11, 19, 14,  2, 13, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 11, 17, 12, 18,  6, 11, 
     0, 30, 31, 20, 33, 29, 25, 42, 21, 27, 35, 44, 24, 23, 28, 34, 
    40,  3, 39, 37, 22, 38, 45,  3, 41,  3, 32,  0,  0,  0, 11,  4, 
     0, 30, 31, 20, 33, 29, 25, 42, 21, 27, 35, 44, 24, 23, 28, 34, 
    40,  3, 39, 37, 22, 38, 45,  3, 41,  3, 32, 11, 11, 11,  0,  0, 
     0,  0,  0,  0,  0, 46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0, 
    11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\1\1\4\2\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\3\3\1\1\5\3"+
    "\1\1\5\3\1\14\1\15\1\14\1\16\1\17\1\20"+
    "\1\0\1\3\1\0\1\21\3\22\2\0\2\3\1\23"+
    "\2\3\1\24\2\3\1\0\3\3\1\0\2\3\1\0"+
    "\1\25\1\3\1\25\5\3\2\0\6\3\1\0\1\2"+
    "\4\0\2\3\1\0\2\3\2\26\1\3\1\0\3\3"+
    "\2\0\3\3\1\0\4\3\1\0\4\3\2\0\6\3"+
    "\1\0\1\22\1\27\2\30\1\3\1\0\1\3\1\31"+
    "\1\3\1\0\3\3\2\0\2\3\1\0\3\3\1\32"+
    "\1\0\3\3\1\0\1\3\2\0\2\3\1\33\3\3"+
    "\1\34\1\35\2\36\2\3\1\0\1\3\1\37\1\40"+
    "\1\41\11\0\1\41\1\42\1\0\3\3\1\0\1\3"+
    "\1\43\1\44\1\0\1\3\2\0\2\3\1\45\1\46"+
    "\1\47\1\3\1\50\2\51\1\3\2\0\1\52\1\0"+
    "\1\53\14\0\2\54\1\3\1\55\1\0\1\3\2\56"+
    "\2\0\2\3\1\57\3\0\1\60\14\0\1\3\1\0"+
    "\1\3\1\0\2\61\1\3\1\62\1\0\1\63\14\0"+
    "\1\3\2\64\1\0\1\3\1\65\3\0\1\66\1\67"+
    "\1\70\3\0\1\71\2\0\1\72\1\3\1\73\1\74"+
    "\1\0\1\75\1\76\1\0\1\77\1\0\1\100\1\101"+
    "\1\0\1\102\1\0\1\103\1\0\1\104\4\0\1\105"+
    "\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\215\0\u0178\0\u01a7\0\215\0\215\0\215\0\215\0\215"+
    "\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f"+
    "\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\215"+
    "\0\215\0\u0497\0\215\0\215\0\215\0\u04c6\0\u04f5\0\u011a"+
    "\0\215\0\u0524\0\u0553\0\215\0\u0149\0\u0582\0\u05b1\0\u05e0"+
    "\0\353\0\u060f\0\u063e\0\353\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\215\0\u0843"+
    "\0\353\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u04c6"+
    "\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\u0c7c\0\215\0\353\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf"+
    "\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057"+
    "\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf"+
    "\0\u0b33\0\215\0\215\0\353\0\u11fe\0\u122d\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403"+
    "\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\353\0\u151d\0\u154c"+
    "\0\u157b\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4"+
    "\0\353\0\u16f3\0\u1722\0\u1751\0\215\0\353\0\215\0\353"+
    "\0\u1780\0\u17af\0\u17de\0\u180d\0\u183c\0\353\0\215\0\u186b"+
    "\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\u1985\0\u19b4\0\u19e3"+
    "\0\353\0\353\0\u1a12\0\u1a41\0\u1a70\0\u1a9f\0\u1ace\0\u1afd"+
    "\0\353\0\353\0\u1b2c\0\u1b5b\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17"+
    "\0\353\0\353\0\353\0\u1c46\0\353\0\215\0\353\0\u1c75"+
    "\0\u1ca4\0\u1cd3\0\215\0\u1d02\0\215\0\u1d31\0\u1d60\0\u1d8f"+
    "\0\u1dbe\0\u1ded\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9\0\u1ed8\0\u1f07"+
    "\0\u1f36\0\215\0\353\0\u1f65\0\353\0\u1f94\0\u1fc3\0\215"+
    "\0\353\0\u1ff2\0\u2021\0\u2050\0\u207f\0\353\0\u20ae\0\u20dd"+
    "\0\u210c\0\215\0\u213b\0\u216a\0\u2199\0\u21c8\0\u21f7\0\u2226"+
    "\0\u2255\0\u2284\0\u22b3\0\u22e2\0\u2311\0\u2340\0\u236f\0\u239e"+
    "\0\u23cd\0\u23fc\0\215\0\353\0\u242b\0\215\0\u245a\0\u2489"+
    "\0\u24b8\0\u24e7\0\u2516\0\u2545\0\u2574\0\u25a3\0\u25d2\0\u2601"+
    "\0\u2630\0\u265f\0\u268e\0\u26bd\0\u26ec\0\215\0\353\0\u271b"+
    "\0\u274a\0\215\0\u2779\0\u27a8\0\u27d7\0\u2806\0\215\0\215"+
    "\0\u2835\0\u2864\0\u2893\0\215\0\u28c2\0\u28f1\0\215\0\u2920"+
    "\0\215\0\353\0\u294f\0\215\0\215\0\u297e\0\215\0\u29ad"+
    "\0\215\0\215\0\u29dc\0\353\0\u2a0b\0\215\0\u2a3a\0\215"+
    "\0\u2a69\0\u2a98\0\u2ac7\0\u2af6\0\215\0\215";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\4\2\6\1\7\1\10\1\11\1\12"+
    "\2\11\1\4\1\13\2\4\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\6\1\22\2\6\1\23\1\24\1\25"+
    "\1\6\1\26\1\27\1\30\2\6\1\31\1\6\1\32"+
    "\1\33\1\6\1\34\1\35\1\6\1\36\1\4\1\6"+
    "\1\37\1\0\10\40\3\41\3\40\1\42\37\40\1\0"+
    "\10\43\3\44\1\43\1\45\41\43\61\0\1\5\1\46"+
    "\55\0\1\47\1\0\2\6\17\0\6\6\1\0\11\6"+
    "\1\0\6\6\1\0\2\6\1\0\5\50\1\51\51\50"+
    "\1\0\1\52\1\53\1\54\1\53\2\0\4\55\1\53"+
    "\1\0\7\53\6\54\1\0\11\54\1\0\6\54\1\0"+
    "\2\54\12\0\1\11\62\0\1\56\42\0\1\47\1\0"+
    "\2\6\17\0\1\57\1\60\1\61\1\6\1\62\1\6"+
    "\1\0\3\6\1\63\1\64\3\6\1\65\1\0\1\6"+
    "\1\66\4\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\67\1\70\1\6\1\71\1\72\5\6"+
    "\1\0\6\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\73\1\74\6\6\1\75\1\6\1\0"+
    "\6\6\1\0\2\6\30\0\1\76\11\0\1\77\16\0"+
    "\1\47\1\0\2\6\17\0\3\6\1\100\2\6\1\0"+
    "\6\6\1\101\2\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\1\6\1\102"+
    "\7\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\4\6\1\103\1\6\1\0\1\6\1\104"+
    "\7\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\7\6\1\105\1\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\11\6\1\0\3\6\1\106\2\6\1\0"+
    "\2\6\37\0\1\107\11\0\1\110\7\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\3\6\1\111\5\6\1\0"+
    "\3\6\1\112\2\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\11\6\1\0\1\6\1\113"+
    "\4\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\3\6\1\114\5\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\11\6\1\0\2\6\1\115\3\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\3\6\1\116"+
    "\5\6\1\0\6\6\1\0\2\6\16\0\1\117\42\0"+
    "\1\120\56\0\1\47\1\121\2\6\17\0\6\6\1\0"+
    "\11\6\1\0\6\6\1\0\2\6\2\0\1\52\1\122"+
    "\56\0\1\53\1\0\1\53\6\0\1\53\1\0\7\53"+
    "\50\0\1\123\42\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\11\6\1\124\1\125\5\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\2\6\1\126\3\6\1\0"+
    "\11\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\127\1\130\10\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\10\6\1\131\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\11\6\1\132"+
    "\1\133\5\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\0\2\6\1\134\6\6\1\0\6\6"+
    "\1\0\2\6\27\0\1\135\31\0\1\47\1\0\2\6"+
    "\17\0\2\6\1\136\3\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\11\6\1\0\4\6\1\137\1\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\4\6"+
    "\1\140\4\6\1\0\6\6\1\0\2\6\31\0\1\141"+
    "\3\0\1\142\23\0\1\47\1\0\2\6\17\0\4\6"+
    "\1\143\1\6\1\0\1\6\1\144\7\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\1\6\1\145\7\6\1\0\6\6\1\0\2\6"+
    "\37\0\1\146\21\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\3\6\1\147\5\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\1\150\3\6\1\151"+
    "\1\6\1\0\11\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\2\6\1\152\3\6\1\153"+
    "\1\154\10\6\1\0\6\6\1\0\2\6\2\0\1\47"+
    "\1\0\2\6\17\0\1\155\5\6\1\0\11\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\2\6\1\156\3\6\1\0\11\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\1\157\5\6"+
    "\1\0\11\6\1\0\6\6\1\0\2\6\31\0\1\160"+
    "\60\0\2\161\24\0\1\47\1\0\2\6\17\0\4\6"+
    "\1\162\1\6\1\0\11\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\161\1\163"+
    "\10\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\2\6\1\164\3\6\1\0\11\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\1\6\1\165\7\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\11\6\1\0\1\6\1\166\4\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\4\6\1\167\1\6\1\0"+
    "\11\6\1\0\6\6\1\0\2\6\16\0\1\170\42\0"+
    "\1\6\56\0\1\171\73\0\1\172\104\0\2\173\12\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\11\6\1\173"+
    "\1\174\5\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\3\6\1\175\2\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\25\0\1\176\33\0\1\47\1\0\2\6"+
    "\17\0\1\177\5\6\1\0\11\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\3\6\1\200\5\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\11\6\1\0"+
    "\2\6\1\201\3\6\1\0\2\6\47\0\1\202\11\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\11\6\1\0"+
    "\1\6\1\203\4\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\2\6\1\204\3\6\1\0\11\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\4\6\1\205\1\6\1\0\11\6\1\0\6\6\1\0"+
    "\2\6\5\0\1\206\70\0\1\207\41\0\1\47\1\0"+
    "\1\6\1\210\17\0\6\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\11\0\1\207"+
    "\5\0\6\6\1\0\11\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\6\6"+
    "\1\211\2\6\1\0\6\6\1\0\2\6\53\0\1\212"+
    "\5\0\1\47\1\0\2\6\17\0\6\6\1\0\11\6"+
    "\1\0\5\6\1\213\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\3\6\1\214\5\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\3\6\1\215\5\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\7\6\1\216\1\6\1\0\6\6\1\0\2\6\35\0"+
    "\1\217\23\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\1\6\1\220\7\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\1\6\1\221\4\6\1\0"+
    "\11\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\7\6\1\222\1\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\223\1\224\10\6\1\0\6\6\1\0\2\6"+
    "\27\0\1\225\64\0\1\226\23\0\1\47\1\0\2\6"+
    "\17\0\2\6\1\227\3\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\1\6\1\230\7\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\3\6"+
    "\1\231\5\6\1\0\6\6\1\0\2\6\2\0\1\47"+
    "\1\0\2\6\17\0\6\6\1\0\2\6\1\232\6\6"+
    "\1\0\6\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\0\11\6\1\0\3\6\1\233\2\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\7\6\1\234\1\6\1\0\6\6\1\0\2\6"+
    "\7\0\1\235\51\0\1\47\1\0\2\6\17\0\4\6"+
    "\1\236\1\6\1\0\11\6\1\0\6\6\1\0\2\6"+
    "\54\0\2\237\3\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\11\6\1\0\6\6\1\237\1\240\1\6\2\0"+
    "\1\47\1\0\1\6\1\241\17\0\6\6\1\0\11\6"+
    "\1\0\6\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\0\11\6\1\0\3\6\1\242\2\6"+
    "\1\0\2\6\31\0\1\243\27\0\1\47\1\0\2\6"+
    "\17\0\4\6\1\244\1\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\7\6\1\245\1\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\3\6"+
    "\1\246\5\6\1\0\6\6\1\0\2\6\27\0\1\247"+
    "\54\0\1\250\1\0\1\251\2\0\1\252\2\253\1\0"+
    "\1\254\1\0\1\255\2\0\1\256\1\0\2\257\2\0"+
    "\1\260\7\0\1\47\1\0\2\6\17\0\2\6\1\261"+
    "\3\6\1\0\11\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\7\6\1\262"+
    "\1\6\1\0\6\6\1\0\2\6\36\0\1\263\22\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\2\6\1\264"+
    "\6\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\4\6\1\265\4\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\1\266\5\6\1\0\11\6\1\0\6\6\1\0\2\6"+
    "\36\0\1\267\22\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\2\6\1\270\6\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\7\6"+
    "\1\271\1\6\1\0\6\6\1\0\2\6\2\0\1\47"+
    "\1\0\2\6\17\0\6\6\1\0\1\6\1\272\7\6"+
    "\1\0\6\6\1\0\2\6\43\0\1\273\15\0\1\47"+
    "\1\0\2\6\17\0\6\6\1\0\7\6\1\274\1\6"+
    "\1\0\6\6\1\0\2\6\43\0\1\275\50\0\1\276"+
    "\23\0\1\47\1\0\2\6\17\0\6\6\1\0\7\6"+
    "\1\277\1\6\1\0\6\6\1\0\2\6\2\0\1\47"+
    "\1\0\2\6\17\0\6\6\1\0\1\6\1\300\7\6"+
    "\1\0\6\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\4\6\1\301\1\6\1\0\11\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\2\6\17\0\6\6"+
    "\1\0\7\6\1\302\1\6\1\0\6\6\1\0\2\6"+
    "\2\0\1\47\1\0\2\6\17\0\6\6\1\0\11\6"+
    "\1\0\2\6\1\303\3\6\1\0\2\6\2\0\1\47"+
    "\1\0\2\6\17\0\2\6\1\304\3\6\1\0\11\6"+
    "\1\0\6\6\1\0\2\6\2\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\0\7\6\1\305\1\6\1\0\6\6"+
    "\1\0\2\6\43\0\1\306\15\0\1\47\1\0\2\6"+
    "\17\0\6\6\1\0\7\6\1\307\1\6\1\0\6\6"+
    "\1\0\2\6\2\0\1\47\1\0\1\6\1\310\17\0"+
    "\6\6\1\0\11\6\1\0\6\6\1\0\2\6\25\0"+
    "\1\311\1\312\1\313\7\0\1\314\1\315\3\0\1\316"+
    "\2\0\1\317\42\0\2\320\1\0\1\321\1\322\52\0"+
    "\2\323\52\0\1\324\63\0\1\325\64\0\1\326\64\0"+
    "\1\327\56\0\1\330\44\0\1\331\54\0\1\332\23\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\1\6\1\333"+
    "\7\6\1\0\6\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\2\6\1\334\6\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\2\6\1\335\6\6\1\0\6\6\1\0"+
    "\2\6\37\0\1\336\21\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\3\6\1\337\5\6\1\0\6\6\1\0"+
    "\2\6\35\0\1\340\23\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\1\6\1\341\7\6\1\0\6\6\1\0"+
    "\2\6\17\0\1\342\75\0\1\343\22\0\1\47\1\0"+
    "\2\6\11\0\1\342\5\0\6\6\1\0\11\6\1\0"+
    "\6\6\1\0\2\6\2\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\2\6\1\344\6\6\1\0\6\6\1\0"+
    "\2\6\2\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\2\6\1\345\6\6\1\0\6\6\1\0\2\6\2\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\3\6\1\346"+
    "\5\6\1\0\6\6\1\0\2\6\45\0\2\347\37\0"+
    "\1\350\73\0\1\351\57\0\2\352\46\0\1\353\47\0"+
    "\1\354\101\0\1\355\44\0\1\356\47\0\1\357\64\0"+
    "\1\360\44\0\1\361\3\0\1\362\54\0\1\363\54\0"+
    "\1\364\64\0\2\365\57\0\1\366\23\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\5\6\1\367\3\6\1\0"+
    "\6\6\1\0\2\6\42\0\1\370\16\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\6\6\1\371\2\6\1\0"+
    "\6\6\1\0\2\6\32\0\1\372\74\0\1\373\10\0"+
    "\1\47\1\0\2\6\17\0\6\6\1\0\11\6\1\0"+
    "\2\6\1\374\3\6\1\0\2\6\2\0\1\47\1\0"+
    "\2\6\17\0\6\6\1\0\11\6\1\0\4\6\1\375"+
    "\1\6\1\0\2\6\45\0\2\376\40\0\1\377\65\0"+
    "\1\u0100\67\0\1\u0101\55\0\1\u0102\36\0\1\u0103\60\0"+
    "\1\u0104\32\0\1\u0105\124\0\1\u0106\42\0\1\u0107\56\0"+
    "\1\u0108\62\0\1\u0109\46\0\2\u010a\57\0\1\u010b\57\0"+
    "\1\u010c\22\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\3\6\1\u010d\5\6\1\0\6\6\1\0\2\6\43\0"+
    "\1\u010e\15\0\1\47\1\0\2\6\17\0\6\6\1\0"+
    "\7\6\1\u010f\1\6\1\0\6\6\1\0\2\6\33\0"+
    "\2\u0110\24\0\1\47\1\0\2\6\17\0\2\6\1\u0111"+
    "\3\6\1\0\11\6\1\0\6\6\1\0\2\6\31\0"+
    "\1\u0112\32\0\1\u0113\122\0\1\u0114\36\0\1\u0115\70\0"+
    "\1\u0116\52\0\1\u0117\46\0\1\u0118\65\0\1\u0119\60\0"+
    "\1\u011a\43\0\1\u011b\66\0\1\u011c\64\0\1\u011d\50\0"+
    "\1\u011e\52\0\1\u011f\27\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\6\6\1\u0120\2\6\1\0\6\6\1\0"+
    "\2\6\35\0\1\u0121\23\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\7\6\1\u0122\1\6\1\0\6\6\1\0"+
    "\2\6\27\0\1\u0123\72\0\1\u0124\56\0\1\u0125\20\0"+
    "\1\u0126\106\0\1\u0127\57\0\1\u0128\56\0\1\u0129\55\0"+
    "\1\u012a\57\0\1\u012b\22\0\1\47\1\0\2\6\17\0"+
    "\6\6\1\0\7\6\1\u012c\1\6\1\0\6\6\1\0"+
    "\2\6\36\0\1\u012d\57\0\1\u012e\60\0\1\u012f\65\0"+
    "\1\u0130\60\0\1\u0131\43\0\1\u0132\46\0\1\u0133\71\0"+
    "\1\u0134\57\0\1\u0135\56\0\1\u0136\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11045];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\2\1\5\11\17\1\2\11"+
    "\1\1\3\11\1\0\1\1\1\0\1\11\2\1\1\11"+
    "\2\0\10\1\1\0\3\1\1\0\2\1\1\0\1\11"+
    "\7\1\2\0\6\1\1\0\1\1\4\0\2\1\1\0"+
    "\2\1\1\11\2\1\1\0\3\1\2\0\3\1\1\0"+
    "\4\1\1\0\4\1\2\0\6\1\1\0\1\1\2\11"+
    "\2\1\1\0\3\1\1\0\3\1\2\0\2\1\1\0"+
    "\4\1\1\0\3\1\1\0\1\1\2\0\6\1\1\11"+
    "\1\1\1\11\3\1\1\0\3\1\1\11\11\0\2\1"+
    "\1\0\3\1\1\0\3\1\1\0\1\1\2\0\7\1"+
    "\1\11\2\1\2\0\1\11\1\0\1\11\14\0\1\11"+
    "\3\1\1\0\1\1\1\11\1\1\2\0\3\1\3\0"+
    "\1\11\14\0\1\1\1\0\1\1\1\0\1\11\2\1"+
    "\1\11\1\0\1\1\14\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\11\3\0\1\1\2\11\3\0\1\11\2\0"+
    "\1\11\1\1\1\11\1\1\1\0\2\11\1\0\1\11"+
    "\1\0\2\11\1\0\1\1\1\0\1\11\1\0\1\11"+
    "\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

public String comentario = "";
public String texto = "";
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scannerCH(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(symCH.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Error: <<"+yytext()+">> ["+yyline+" , "+yycolumn+"]");
                             return new Symbol(symCH.error, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 2: 
            { return new Symbol(symCH.numero, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 3: 
            { return new Symbol(symCH.identificador, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 4: 
            { return new Symbol(symCH.mayor, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 5: 
            { /*ignorados*/
            }
          case 75: break;
          case 6: 
            { return new Symbol(symCH.menor, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 7: 
            { return new Symbol(symCH.pqa, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 8: 
            { return new Symbol(symCH.pqc, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 9: 
            { return new Symbol(symCH.pyc, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 10: 
            { return new Symbol(symCH.igual, yycolumn, yyline, yytext());
            }
          case 80: break;
          case 11: 
            { return new Symbol(symCH.coma, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 12: 
            { comentario+= yytext();
            }
          case 82: break;
          case 13: 
            { /*se ignora*/
            }
          case 83: break;
          case 14: 
            { texto += yytext();
            }
          case 84: break;
          case 15: 
            { /*Se ignora*/
            }
          case 85: break;
          case 16: 
            { String lexema = texto + yytext();
                             texto = "";
                             yybegin(YYINITIAL);
                             lexema = lexema.substring(1,lexema.length()-1);
                             lexema = lexema.replace("\n", ""); lexema = lexema.replace("\"", "\\\"");
                             return new Symbol(symCH.texto, yycolumn, yyline, lexema);
            }
          case 86: break;
          case 17: 
            { String lexema = yytext().substring(1,yytext().length()-1); lexema = lexema.replace("\n", ""); lexema = lexema.replace("\"", "\\\""); return new Symbol(symCH.cadena, yycolumn, yyline, lexema);
            }
          case 87: break;
          case 18: 
            { texto = yytext();
                             yybegin(TEXTO);
            }
          case 88: break;
          case 19: 
            { return new Symbol(symCH.t_ct, yycolumn, yyline, yytext());
            }
          case 89: break;
          case 20: 
            { return new Symbol(symCH.t_cb, yycolumn, yyline, yytext());
            }
          case 90: break;
          case 21: 
            { return new Symbol(symCH.t_id, yycolumn, yyline, yytext());
            }
          case 91: break;
          case 22: 
            { return new Symbol(symCH.t_cjs, yycolumn, yyline, yytext());
            }
          case 92: break;
          case 23: 
            { yybegin(COMENTARIO);
            }
          case 93: break;
          case 24: 
            { return new Symbol(symCH.t_ccss, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 25: 
            { return new Symbol(symCH.t_caja, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 26: 
            { return new Symbol(symCH.t_alto, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 27: 
            { return new Symbol(symCH.t_ruta, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 28: 
            { comentario ="";
                             yybegin(YYINITIAL);
            }
          case 98: break;
          case 29: 
            { return new Symbol(symCH.t_chtml, yycolumn, yyline, yytext());
            }
          case 99: break;
          case 30: 
            { return new Symbol(symCH.t_click, yycolumn, yyline, yytext());
            }
          case 100: break;
          case 31: 
            { return new Symbol(symCH.t_texto, yycolumn, yyline, yytext());
            }
          case 101: break;
          case 32: 
            { return new Symbol(symCH.t_tabla, yycolumn, yyline, yytext());
            }
          case 102: break;
          case 33: 
            { return new Symbol(symCH.t_fil_t, yycolumn, yyline, yytext());
            }
          case 103: break;
          case 34: 
            { return new Symbol(symCH.t_fondo, yycolumn, yyline, yytext());
            }
          case 104: break;
          case 35: 
            { return new Symbol(symCH.t_ancho, yycolumn, yyline, yytext());
            }
          case 105: break;
          case 36: 
            { return new Symbol(symCH.t_boton, yycolumn, yyline, yytext());
            }
          case 106: break;
          case 37: 
            { return new Symbol(symCH.t_panel, yycolumn, yyline, yytext());
            }
          case 107: break;
          case 38: 
            { return new Symbol(symCH.t_grupo, yycolumn, yyline, yytext());
            }
          case 108: break;
          case 39: 
            { return new Symbol(symCH.t_valor, yycolumn, yyline, yytext());
            }
          case 109: break;
          case 40: 
            { return new Symbol(symCH.t_cuerpo, yycolumn, yyline, yytext());
            }
          case 110: break;
          case 41: 
            { return new Symbol(symCH.t_titulo, yycolumn, yyline, yytext());
            }
          case 111: break;
          case 42: 
            { return new Symbol(symCH.t_fin_ct, yycolumn, yyline, yytext());
            }
          case 112: break;
          case 43: 
            { return new Symbol(symCH.t_fin_cb, yycolumn, yyline, yytext());
            }
          case 113: break;
          case 44: 
            { return new Symbol(symCH.t_imagen, yycolumn, yyline, yytext());
            }
          case 114: break;
          case 45: 
            { return new Symbol(symCH.t_enlace, yycolumn, yyline, yytext());
            }
          case 115: break;
          case 46: 
            { return new Symbol(symCH.t_opcion, yycolumn, yyline, yytext());
            }
          case 116: break;
          case 47: 
            { return new Symbol(symCH.t_texto_a, yycolumn, yyline, yytext());
            }
          case 117: break;
          case 48: 
            { return new Symbol(symCH.t_fin_cjs, yycolumn, yyline, yytext());
            }
          case 118: break;
          case 49: 
            { return new Symbol(symCH.t_spinner, yycolumn, yyline, yytext());
            }
          case 119: break;
          case 50: 
            { return new Symbol(symCH.t_fin_ccss, yycolumn, yyline, yytext());
            }
          case 120: break;
          case 51: 
            { return new Symbol(symCH.t_fin_caja, yycolumn, yyline, yytext());
            }
          case 121: break;
          case 52: 
            { return new Symbol(symCH.t_alineado, yycolumn, yyline, yytext());
            }
          case 122: break;
          case 53: 
            { return new Symbol(symCH.t_fin_chtml, yycolumn, yyline, yytext());
            }
          case 123: break;
          case 54: 
            { return new Symbol(symCH.t_fin_texto, yycolumn, yyline, yytext());
            }
          case 124: break;
          case 55: 
            { return new Symbol(symCH.t_fin_tabla, yycolumn, yyline, yytext());
            }
          case 125: break;
          case 56: 
            { return new Symbol(symCH.t_fin_fil_t, yycolumn, yyline, yytext());
            }
          case 126: break;
          case 57: 
            { return new Symbol(symCH.t_fin_boton, yycolumn, yyline, yytext());
            }
          case 127: break;
          case 58: 
            { return new Symbol(symCH.t_fin_panel, yycolumn, yyline, yytext());
            }
          case 128: break;
          case 59: 
            { return new Symbol(symCH.t_salto_fin, yycolumn, yyline, yytext());
            }
          case 129: break;
          case 60: 
            { return new Symbol(symCH.t_caja_texto, yycolumn, yyline, yytext());
            }
          case 130: break;
          case 61: 
            { return new Symbol(symCH.t_fin_cuerpo, yycolumn, yyline, yytext());
            }
          case 131: break;
          case 62: 
            { return new Symbol(symCH.t_fin_titulo, yycolumn, yyline, yytext());
            }
          case 132: break;
          case 63: 
            { return new Symbol(symCH.t_fin_imagen, yycolumn, yyline, yytext());
            }
          case 133: break;
          case 64: 
            { return new Symbol(symCH.t_fin_enlace, yycolumn, yyline, yytext());
            }
          case 134: break;
          case 65: 
            { return new Symbol(symCH.t_fin_opcion, yycolumn, yyline, yytext());
            }
          case 135: break;
          case 66: 
            { return new Symbol(symCH.t_encabezado, yycolumn, yyline, yytext());
            }
          case 136: break;
          case 67: 
            { return new Symbol(symCH.t_fin_texto_a, yycolumn, yyline, yytext());
            }
          case 137: break;
          case 68: 
            { return new Symbol(symCH.t_fin_spinner, yycolumn, yyline, yytext());
            }
          case 138: break;
          case 69: 
            { return new Symbol(symCH.t_fin_caja_texto, yycolumn, yyline, yytext());
            }
          case 139: break;
          case 70: 
            { return new Symbol(symCH.t_fin_encabezado, yycolumn, yyline, yytext());
            }
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
