
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 28 03:40:38 CST 2018
//----------------------------------------------------

package GeneradorCHTML;

/** CUP generated class containing symbol constants. */
public class symCH {
  /* terminals */
  public static final int t_fin_ccss = 61;
  public static final int t_fin_cb = 40;
  public static final int t_opcion = 47;
  public static final int t_enlace = 33;
  public static final int t_ct = 41;
  public static final int t_titulo = 19;
  public static final int pqc = 9;
  public static final int t_fin_encabezado = 16;
  public static final int t_texto = 25;
  public static final int pqa = 8;
  public static final int t_alto = 56;
  public static final int t_texto_a = 43;
  public static final int t_fin_texto = 26;
  public static final int coma = 12;
  public static final int igual = 11;
  public static final int t_ruta = 53;
  public static final int identificador = 2;
  public static final int t_caja_texto = 27;
  public static final int t_boton = 31;
  public static final int t_cb = 39;
  public static final int t_ccss = 60;
  public static final int t_id = 54;
  public static final int t_fin_boton = 32;
  public static final int t_fin_cuerpo = 22;
  public static final int t_ancho = 57;
  public static final int t_fin_caja = 46;
  public static final int numero = 3;
  public static final int t_fondo = 59;
  public static final int t_imagen = 29;
  public static final int t_fin_texto_a = 44;
  public static final int t_spinner = 49;
  public static final int t_fin_opcion = 48;
  public static final int menor = 6;
  public static final int EOF = 0;
  public static final int t_fin_enlace = 34;
  public static final int t_salto_fin = 51;
  public static final int pyc = 10;
  public static final int t_fin_titulo = 20;
  public static final int error = 1;
  public static final int mayor = 7;
  public static final int t_fin_caja_texto = 28;
  public static final int t_caja = 45;
  public static final int t_panel = 23;
  public static final int t_grupo = 55;
  public static final int t_fin_panel = 24;
  public static final int t_fin_spinner = 50;
  public static final int t_fil_t = 37;
  public static final int t_tabla = 35;
  public static final int t_chtml = 13;
  public static final int t_encabezado = 15;
  public static final int texto = 4;
  public static final int t_fin_fil_t = 38;
  public static final int t_fin_tabla = 36;
  public static final int t_fin_chtml = 14;
  public static final int t_fin_ct = 42;
  public static final int t_fin_imagen = 30;
  public static final int t_valor = 62;
  public static final int t_cuerpo = 21;
  public static final int t_alineado = 58;
  public static final int t_fin_cjs = 18;
  public static final int t_click = 52;
  public static final int t_cjs = 17;
  public static final int cadena = 5;
}

