
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 22 16:33:31 CST 2018
//----------------------------------------------------

package GeneradorCHTML;

/** CUP generated class containing symbol constants. */
public class symCH {
  /* terminals */
  public static final int ancho = 34;
  public static final int finimagen = 45;
  public static final int fincb = 50;
  public static final int fondo = 14;
  public static final int texto_t = 13;
  public static final int finspinner = 55;
  public static final int fincaja = 53;
  public static final int imagen = 16;
  public static final int caja_texto = 15;
  public static final int CAD2 = 59;
  public static final int alto = 33;
  public static final int CAD = 58;
  public static final int IGUAL = 5;
  public static final int texto_a = 24;
  public static final int panel = 12;
  public static final int finpanel = 42;
  public static final int grupo = 32;
  public static final int fincaja_texto = 44;
  public static final int alineado = 35;
  public static final int ruta = 30;
  public static final int NUM = 56;
  public static final int ccss = 9;
  public static final int ID = 57;
  public static final int tabla = 19;
  public static final int PUNTO_COMA = 2;
  public static final int chtml = 6;
  public static final int fil_t = 20;
  public static final int finfil_t = 49;
  public static final int fintabla = 48;
  public static final int finchtml = 36;
  public static final int ct = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int fincuerpo = 41;
  public static final int MENOR = 3;
  public static final int valor = 23;
  public static final int cuerpo = 11;
  public static final int spinner = 27;
  public static final int click = 29;
  public static final int cb = 21;
  public static final int MAYOR = 4;
  public static final int id = 31;
  public static final int finopcion = 54;
  public static final int finenlace = 47;
  public static final int opcion = 26;
  public static final int cjs = 8;
  public static final int fintitulo = 40;
  public static final int enlace = 18;
  public static final int finccss = 39;
  public static final int titulo = 10;
  public static final int fincjs = 38;
  public static final int encabezado = 7;
  public static final int caja = 25;
  public static final int fintexto = 43;
  public static final int salto = 28;
  public static final int fintexto_a = 52;
  public static final int finct = 51;
  public static final int finencabezado = 37;
  public static final int boton = 17;
  public static final int finboton = 46;
}

