
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 22 01:17:28 CST 2018
//----------------------------------------------------

package GeneradorCHTML;

/** CUP generated class containing symbol constants. */
public class symCH {
  /* terminals */
  public static final int pr_finct = 54;
  public static final int pr_finboton = 49;
  public static final int pr_fincaja_texto = 47;
  public static final int pr_boton = 18;
  public static final int pr_finccss = 42;
  public static final int pr_ancho = 35;
  public static final int pr_atri_ccss = 37;
  public static final int pr_fincb = 53;
  public static final int coma = 6;
  public static final int pr_fondo = 15;
  public static final int igual = 5;
  public static final int identificador = 63;
  public static final int pr_fintexto_a = 55;
  public static final int pr_encabezado = 8;
  public static final int saltos = 62;
  public static final int ptodo = 38;
  public static final int pr_cjs = 9;
  public static final int otro_simb = 67;
  public static final int pr_fincaja = 56;
  public static final int pr_alto = 34;
  public static final int pr_finpanel = 45;
  public static final int pr_fincuerpo = 44;
  public static final int pr_panel = 13;
  public static final int numero = 61;
  public static final int pr_alineado = 36;
  public static final int pr_grupo = 33;
  public static final int simb = 68;
  public static final int menor = 3;
  public static final int pr_ruta = 31;
  public static final int pr_cuerpo = 12;
  public static final int cadena2 = 66;
  public static final int EOF = 0;
  public static final int pr_finfil_t = 52;
  public static final int pr_fintabla = 51;
  public static final int pr_finchtml = 39;
  public static final int error = 1;
  public static final int pr_finspinner = 58;
  public static final int pr_finenlace = 50;
  public static final int pr_chtml = 7;
  public static final int pr_ccss = 10;
  public static final int pr_fil_t = 21;
  public static final int pr_tabla = 20;
  public static final int pr_finopcion = 57;
  public static final int mayor = 4;
  public static final int pr_finencabezado = 40;
  public static final int pr_texto_a = 25;
  public static final int pr_fintitulo = 43;
  public static final int pr_ct = 23;
  public static final int pr_enlace = 19;
  public static final int pr_opcion = 27;
  public static final int pr_caja_texto = 16;
  public static final int pr_fincjs = 41;
  public static final int pr_valor = 24;
  public static final int pr_titulo = 11;
  public static final int pr_click = 30;
  public static final int texto = 64;
  public static final int pr_cb = 22;
  public static final int pr_id = 32;
  public static final int pr_spinner = 28;
  public static final int pr_fintexto = 46;
  public static final int pr_texto = 14;
  public static final int pr_caja = 26;
  public static final int pr_salto = 29;
  public static final int pr_finimagen = 48;
  public static final int pr_parC = 59;
  public static final int pr_parA = 60;
  public static final int cadena = 65;
  public static final int pr_imagen = 17;
  public static final int p_coma = 2;
}

